"""Initial migration

Revision ID: 6cdb435d105a
Revises: 
Create Date: 2025-07-05 17:21:50.427671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdb435d105a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(
            'fk_reaction_post_id',   # constraint name
            'post',                  # referent table
            ['post_id'],             # local column
            ['id']                   # remote column
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reaction_post_id', type_='foreignkey')
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
